ALTER TABLE "users"
  ADD COLUMN "reminderEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "reminderHour" INTEGER NOT NULL DEFAULT 19,
  ADD COLUMN "reminderMinute" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "reminderDays" INTEGER[] NOT NULL DEFAULT ARRAY[1, 2, 3, 4, 5],
  ADD COLUMN "reminderTimezone" TEXT NOT NULL DEFAULT 'UTC';
