CREATE TYPE "QuizMode" AS ENUM ('FORWARD', 'REVERSE', 'TYPED', 'CLOZE', 'LISTENING', 'MISTAKES', 'DIFFICULT');

ALTER TABLE "test_questions"
  ADD COLUMN "mode" "QuizMode" NOT NULL DEFAULT 'FORWARD';
