/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and obtain an access + refresh token pair
         * @description On success, the refresh token is BOTH set as an `httpOnly` cookie (for web clients) AND returned in the JSON body (for mobile / non-cookie clients).
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive an access + refresh token pair */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token into a new access + refresh pair
         * @description The refresh token is read from the `refresh_token` httpOnly cookie if present, otherwise from the JSON body. The old token is invalidated; replaying a revoked token revokes the entire user refresh chain.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a single refresh token (sign-out for this device)
         * @description Clears the `refresh_token` cookie and deletes the matching row. Idempotent — succeeds even if the token is already unknown.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current authenticated user */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password for the current authenticated user
         * @description Requires the current password for verification. The current JWT remains valid after a password change.
         */
        post: operations["UsersController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List words owned by the current user (paginated) */
        get: operations["WordsController_findAll"];
        put?: never;
        /** Create a new word in the user vocabulary */
        post: operations["WordsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a word owned by the current user */
        delete: operations["WordsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get today's words to review (spaced repetition) */
        get: operations["LearningController_getDailyWords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a review for a word */
        post: operations["LearningController_reviewWord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a new quiz from the user vocabulary */
        post: operations["TestsController_startTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a completed quiz and receive the result */
        post: operations["TestsController_submitTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vocabulary and test statistics for the current user */
        get: operations["ProgressController_getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — does the API process respond? */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — API + database reachable */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserResponseDto: {
            /**
             * Format: uuid
             * @example 8c5f4e64-1c39-4a55-9c8e-1e1b9c41a0a2
             */
            id: string;
            /**
             * Format: email
             * @example student@example.com
             */
            email: string;
            /**
             * Format: date-time
             * @example 2026-05-11T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-11T12:00:00.000Z
             */
            updatedAt: string;
        };
        AuthResponseDto: {
            user: components["schemas"]["UserResponseDto"];
            /**
             * @description Short-lived JWT (default 15 min). Send as `Authorization: Bearer <token>` on authenticated requests.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description Opaque long-lived refresh token (default 30 days). POST to /auth/refresh to rotate this into a new access + refresh pair when the access token expires.
             * @example h6XdR3pK8c-NlYvQ3jKz2hYW9bP5MZeT7vL_8nXrSc
             */
            refreshToken: string;
        };
        RegisterDto: {
            /**
             * Format: email
             * @example student@example.com
             */
            email: string;
            /**
             * @description Plain text password, hashed server-side with bcrypt. Must contain at least one letter and one digit.
             * @example StrongPass123!
             */
            password: string;
        };
        ApiErrorResponseDto: {
            /** @example false */
            success: boolean;
            /** @example 400 */
            statusCode: number;
            /** @example Validation failed */
            message: string;
            /** @example Bad Request */
            error: string;
            /**
             * @description Present for validation errors
             * @example [
             *       "email must be an email"
             *     ]
             */
            errors?: string[];
            /** @example /auth/register */
            path: string;
            /**
             * Format: date-time
             * @example 2026-05-11T12:00:00.000Z
             */
            timestamp: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example student@example.com
             */
            email: string;
            /** @example StrongPass123! */
            password: string;
        };
        RefreshTokenDto: {
            /**
             * @description Opaque refresh token. Optional when the request carries the `refresh_token` httpOnly cookie (web clients).
             * @example h6XdR3pK8c-NlYvQ3jKz2hYW9bP5MZeT7vL_8nXrSc
             */
            refreshToken?: string;
        };
        UpdateUserDto: {
            /**
             * @description New email address. Must be unique.
             * @example new-email@example.com
             */
            email?: string;
            /**
             * @description The current password — required when changing email to prevent account takeover via stolen access tokens. Ignored when no email change is requested.
             * @example CurrentPass123!
             */
            currentPassword: string;
        };
        ChangePasswordDto: {
            /**
             * @description The user's current password
             * @example CurrentPass123!
             */
            currentPassword: string;
            /**
             * @description The new password. Must contain at least one letter and one digit.
             * @example NewStrongerPass456!
             */
            newPassword: string;
        };
        WordResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example serendipity */
            word: string;
            /** @example kutilmagan yoqimli kashfiyot */
            translation: string;
            /** @example Finding that book was pure serendipity. */
            example?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateWordDto: {
            /** @example serendipity */
            word: string;
            /** @example kutilmagan yoqimli kashfiyot */
            translation: string;
            /** @example Finding that book was pure serendipity. */
            example?: string;
        };
        DailyWordResponseDto: {
            /**
             * Format: uuid
             * @description UserWord id (use in /learning/review)
             */
            id: string;
            /** Format: uuid */
            wordId: string;
            /** @example serendipity */
            word: string;
            /** @example kutilmagan yoqimli kashfiyot */
            translation: string;
            example?: Record<string, never>;
            /**
             * @example NEW
             * @enum {string}
             */
            status: "NEW" | "LEARNING" | "LEARNED";
            /** @example 0 */
            repetitionCount: number;
        };
        ReviewResultDto: {
            /** Format: uuid */
            id: string;
            /** @example serendipity */
            word: string;
            /**
             * @example LEARNING
             * @enum {string}
             */
            status: "NEW" | "LEARNING" | "LEARNED";
            /** @example 3 */
            repetitionCount: number;
        };
        ReviewWordDto: {
            /**
             * Format: uuid
             * @description ID of the UserWord (not the Word itself)
             * @example 7a1e0b8f-9c12-4d3a-b8e7-65b1d3c9c2f4
             */
            userWordId: string;
            /**
             * @description Whether the user answered correctly
             * @example true
             */
            correct: boolean;
        };
        TestQuestionDto: {
            /** Format: uuid */
            wordId: string;
            /** @example serendipity */
            word: string;
            /**
             * @example [
             *       "kutilmagan yoqimli kashfiyot",
             *       "jadval",
             *       "iqtisodiy",
             *       "lazzat"
             *     ]
             */
            options: string[];
        };
        StartTestResponseDto: {
            questions: components["schemas"]["TestQuestionDto"][];
        };
        TestQuestionResultDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            wordId: string;
            selectedAnswer: string;
            correctAnswer: string;
        };
        SubmitTestResponseDto: {
            /** Format: uuid */
            testId: string;
            /** @example 4 */
            score: number;
            /** @example 5 */
            total: number;
            /** @example 80 */
            percentage: number;
            questions: components["schemas"]["TestQuestionResultDto"][];
        };
        TestAnswerDto: {
            /**
             * Format: uuid
             * @example b2c1a0d3-5e4f-6789-abcd-ef0123456789
             */
            wordId: string;
            /** @example kutilmagan yoqimli kashfiyot */
            selectedAnswer: string;
        };
        SubmitTestDto: {
            answers: components["schemas"]["TestAnswerDto"][];
        };
        VocabularyStatsDto: {
            /** @example 42 */
            total: number;
            /** @example 10 */
            new: number;
            /** @example 22 */
            learning: number;
            /** @example 10 */
            learned: number;
            /**
             * @description Percentage of learned words (0–100)
             * @example 24
             */
            progressPercentage: number;
        };
        RecentTestDto: {
            /** Format: uuid */
            id: string;
            /** @example 4 */
            score: number;
            /** @example 5 */
            totalQuestions: number;
            /** Format: date-time */
            createdAt: string;
        };
        TestStatsDto: {
            /** @example 12 */
            total: number;
            /**
             * @description Average score across all tests
             * @example 3.8
             */
            averageScore: number;
            recent: components["schemas"]["RecentTestDto"][];
        };
        ProgressResponseDto: {
            vocabulary: components["schemas"]["VocabularyStatsDto"];
            tests: components["schemas"]["TestStatsDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User created and authenticated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["AuthResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["AuthResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["AuthResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Refresh token is missing, invalid, expired, or reused */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Refresh token revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Logged out"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["UserResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Returns the updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["UserResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UsersController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Password updated successfully"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description New password is the same as current, or fails validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Current password is incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    WordsController_findAll: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page (capped at 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: {
                            items: components["schemas"]["WordResponseDto"][];
                            /** @example 137 */
                            total: number;
                            /** @example 1 */
                            page: number;
                            /** @example 20 */
                            limit: number;
                            /** @example true */
                            hasMore: boolean;
                        };
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    WordsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWordDto"];
            };
        };
        responses: {
            /** @description Word created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["WordResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    WordsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Word deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Word deleted successfully"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Word belongs to another user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Word not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    LearningController_getDailyWords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["DailyWordResponseDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    LearningController_reviewWord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewWordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["ReviewResultDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description UserWord does not exist or does not belong to user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    TestsController_startTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["StartTestResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Not enough words to start a test */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    TestsController_submitTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["SubmitTestResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    ProgressController_getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["ProgressResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
