/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and obtain an access + refresh token pair
         * @description On success, the refresh token is BOTH set as an `httpOnly` cookie (for web clients) AND returned in the JSON body (for mobile / non-cookie clients).
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive an access + refresh token pair */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token into a new access + refresh pair
         * @description The refresh token is read from the `refresh_token` httpOnly cookie if present, otherwise from the JSON body. The old token is invalidated; replaying a revoked token revokes the entire user refresh chain.
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a single refresh token (sign-out for this device)
         * @description Clears the `refresh_token` cookie and deletes the matching row. Idempotent — succeeds even if the token is already unknown.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password-reset link
         * @description Always responds 200 regardless of whether the email is registered, so the endpoint cannot be used to discover which emails have accounts. A reset link is emailed only when the account exists.
         */
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset a password using an emailed token
         * @description Consumes a single-use reset token, sets the new password, and invalidates every existing session (access + refresh tokens).
         */
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send an email-verification link to the current user */
        post: operations["AuthController_requestEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an email address using an emailed token */
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        /**
         * Permanently delete the current authenticated account
         * @description Requires the current password. Cascades to all owned data (words, progress, tokens, enrollments, reviews). Irreversible.
         */
        delete: operations["UsersController_deleteMe"];
        options?: never;
        head?: never;
        /** Update current authenticated user */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/users/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Complete or skip onboarding
         * @description Records the chosen level, enrolls the user in the selected decks, and marks the account as onboarded. Send an empty deckIds array to skip.
         */
        patch: operations["UsersController_onboarding"];
        trace?: never;
    };
    "/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change password for the current authenticated user
         * @description Requires the current password for verification. The current JWT remains valid after a password change.
         */
        post: operations["UsersController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse system and public decks (paginated) */
        get: operations["DecksController_findAll"];
        put?: never;
        /** Create a personal deck */
        post: operations["DecksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decks the current user has joined or created */
        get: operations["DecksController_findMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deck detail with its words */
        get: operations["DecksController_findOne"];
        put?: never;
        post?: never;
        /** Delete a deck the current user created */
        delete: operations["DecksController_remove"];
        options?: never;
        head?: never;
        /** Edit a deck the current user created */
        patch: operations["DecksController_update"];
        trace?: never;
    };
    "/decks/{id}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a deck — adds its words to your learning list */
        post: operations["DecksController_enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{id}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add words to a deck the current user created */
        post: operations["DecksController_addWords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{id}/words/{wordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a word from a deck the current user created */
        delete: operations["DecksController_removeWord"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a curated system deck (admin) */
        post: operations["AdminDecksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/decks/{id}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add words to any deck (admin) */
        post: operations["AdminDecksController_addWords"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/decks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete any deck (admin) */
        delete: operations["AdminDecksController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List words owned by the current user (paginated) */
        get: operations["WordsController_findAll"];
        put?: never;
        /** Create a new word in the user vocabulary */
        post: operations["WordsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/words/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a word owned by the current user */
        delete: operations["WordsController_remove"];
        options?: never;
        head?: never;
        /** Edit a word owned by the current user */
        patch: operations["WordsController_update"];
        trace?: never;
    };
    "/learning/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get today's words to review (spaced repetition) */
        get: operations["LearningController_getDailyWords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a review for a word */
        post: operations["LearningController_reviewWord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a new quiz from the user vocabulary */
        post: operations["TestsController_startTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tests/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a completed quiz and receive the result */
        post: operations["TestsController_submitTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vocabulary and test statistics for the current user */
        get: operations["ProgressController_getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily review activity over a trailing window (zero-filled) */
        get: operations["ProgressController_getTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-deck learning progress for joined/created decks */
        get: operations["ProgressController_getDeckProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/progress/leeches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Troublesome words with a high lapse count */
        get: operations["ProgressController_getLeeches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — does the API process respond? */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — API + database reachable */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserResponseDto: {
            /**
             * Format: uuid
             * @example 8c5f4e64-1c39-4a55-9c8e-1e1b9c41a0a2
             */
            id: string;
            /**
             * Format: email
             * @example student@example.com
             */
            email: string;
            /**
             * @example A2
             * @enum {string|null}
             */
            level?: "A1" | "A2" | "B1" | "B2" | "C1" | "C2" | null;
            /**
             * Format: date-time
             * @description Null until the user completes or skips onboarding
             */
            onboardedAt?: Record<string, never> | null;
            /**
             * @description Daily review goal (1–200)
             * @example 20
             */
            dailyGoal: number;
            /**
             * @example USER
             * @enum {string}
             */
            role: "USER" | "ADMIN";
            /**
             * Format: date-time
             * @description Null until the user verifies their email
             */
            emailVerifiedAt?: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-05-11T12:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-11T12:00:00.000Z
             */
            updatedAt: string;
        };
        AuthResponseDto: {
            user: components["schemas"]["UserResponseDto"];
            /**
             * @description Short-lived JWT (default 15 min). Send as `Authorization: Bearer <token>` on authenticated requests.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description Opaque long-lived refresh token (default 30 days). POST to /auth/refresh to rotate this into a new access + refresh pair when the access token expires.
             * @example h6XdR3pK8c-NlYvQ3jKz2hYW9bP5MZeT7vL_8nXrSc
             */
            refreshToken: string;
        };
        RegisterDto: {
            /**
             * Format: email
             * @example student@example.com
             */
            email: string;
            /**
             * @description Plain text password, hashed server-side with bcrypt. Must contain at least one letter and one digit.
             * @example StrongPass123!
             */
            password: string;
        };
        ApiErrorResponseDto: {
            /** @example false */
            success: boolean;
            /** @example 400 */
            statusCode: number;
            /** @example Validation failed */
            message: string;
            /** @example Bad Request */
            error: string;
            /**
             * @description Present for validation errors
             * @example [
             *       "email must be an email"
             *     ]
             */
            errors?: string[];
            /** @example /auth/register */
            path: string;
            /**
             * Format: date-time
             * @example 2026-05-11T12:00:00.000Z
             */
            timestamp: string;
        };
        LoginDto: {
            /**
             * Format: email
             * @example student@example.com
             */
            email: string;
            /** @example StrongPass123! */
            password: string;
        };
        RefreshTokenDto: {
            /**
             * @description Opaque refresh token. Optional when the request carries the `refresh_token` httpOnly cookie (web clients).
             * @example h6XdR3pK8c-NlYvQ3jKz2hYW9bP5MZeT7vL_8nXrSc
             */
            refreshToken?: string;
        };
        ForgotPasswordDto: {
            /**
             * Format: email
             * @example student@example.com
             */
            email: string;
        };
        ResetPasswordDto: {
            /**
             * @description The opaque password-reset token delivered by email.
             * @example h6XdR3pK8c-NlYvQ3jKz2hYW9bP5MZeT7vL_8nXrSc
             */
            token: string;
            /**
             * @description The new password. Must contain at least one letter and one digit.
             * @example NewStrongerPass456!
             */
            newPassword: string;
        };
        VerifyEmailDto: {
            /**
             * @description The opaque email-verification token delivered by email.
             * @example h6XdR3pK8c-NlYvQ3jKz2hYW9bP5MZeT7vL_8nXrSc
             */
            token: string;
        };
        UpdateUserDto: {
            /**
             * @description New email address. Must be unique.
             * @example new-email@example.com
             */
            email?: string;
            /**
             * @description Daily review goal (1–200). Editable without the current password.
             * @example 20
             */
            dailyGoal?: number;
            /**
             * @description The current password — required only when changing email, to prevent account takeover via stolen access tokens. Not needed for other updates (e.g. dailyGoal).
             * @example CurrentPass123!
             */
            currentPassword?: string;
        };
        OnboardingDto: {
            /**
             * @description Self-reported level
             * @enum {string}
             */
            level?: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /**
             * @description Decks to enroll in. May be empty when the user skips.
             * @example [
             *       "11111111-1111-1111-1111-111111111111"
             *     ]
             */
            deckIds: string[];
        };
        ChangePasswordDto: {
            /**
             * @description The user's current password
             * @example CurrentPass123!
             */
            currentPassword: string;
            /**
             * @description The new password. Must contain at least one letter and one digit.
             * @example NewStrongerPass456!
             */
            newPassword: string;
        };
        DeleteAccountDto: {
            /**
             * @description The current password — required to confirm account deletion and prevent takeover-then-delete via a stolen access token.
             * @example CurrentPass123!
             */
            currentPassword: string;
        };
        DeckResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example Travel Essentials */
            title: string;
            /** @example Words you need for getting around abroad. */
            description?: Record<string, never>;
            /**
             * @example A2
             * @enum {string}
             */
            level?: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /** @description True for curated decks shipped with the app */
            isSystem: boolean;
            /** @description Whether the deck is shared publicly. Always false for system decks. */
            isPublic: boolean;
            /** @description Whether the current user created (and can edit) this deck */
            isOwner: boolean;
            /**
             * @description Number of words in the deck
             * @example 40
             */
            wordCount: number;
            /** @description Whether the current user has joined this deck */
            isEnrolled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        CreateDeckDto: {
            /** @example My Travel Words */
            title: string;
            /** @example Words I picked up on my trips abroad. */
            description?: string;
            /**
             * @example A2
             * @enum {string}
             */
            level?: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /**
             * @description Make the deck visible to other users
             * @default false
             */
            isPublic: boolean;
        };
        WordResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example serendipity */
            word: string;
            /** @example kutilmagan yoqimli kashfiyot */
            translation: string;
            /** @example Finding that book was pure serendipity. */
            example?: Record<string, never>;
            /** @example https://cdn.example.com/audio/serendipity.mp3 */
            audioUrl?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        DeckDetailResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example Travel Essentials */
            title: string;
            /** @example Words you need for getting around abroad. */
            description?: Record<string, never>;
            /**
             * @example A2
             * @enum {string}
             */
            level?: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /** @description True for curated decks shipped with the app */
            isSystem: boolean;
            /** @description Whether the deck is shared publicly. Always false for system decks. */
            isPublic: boolean;
            /** @description Whether the current user created (and can edit) this deck */
            isOwner: boolean;
            /**
             * @description Number of words in the deck
             * @example 40
             */
            wordCount: number;
            /** @description Whether the current user has joined this deck */
            isEnrolled: boolean;
            /** Format: date-time */
            createdAt: string;
            words: components["schemas"]["WordResponseDto"][];
        };
        EnrollResponseDto: {
            /** @example Enrolled in "Travel Essentials" */
            message: string;
            /**
             * @description Words now in your learning list
             * @example 40
             */
            enrolledCount: number;
        };
        UpdateDeckDto: {
            /** @example My Travel Words */
            title?: string;
            /** @example Words I picked up on my trips abroad. */
            description?: string;
            /**
             * @example A2
             * @enum {string}
             */
            level?: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            /** @description Make the deck visible to other users */
            isPublic?: boolean;
        };
        AddDeckWordsResponseDto: {
            /** @example Added 3 words to "My Travel Words" */
            message: string;
            /**
             * @description Words added by this request
             * @example 3
             */
            addedCount: number;
            /**
             * @description Total words in the deck now
             * @example 12
             */
            wordCount: number;
        };
        DeckWordItemDto: {
            /** @example serendipity */
            word: string;
            /** @example kutilmagan yoqimli kashfiyot */
            translation: string;
            /** @example Finding that book was pure serendipity. */
            example?: string;
            /** @example https://cdn.example.com/audio/serendipity.mp3 */
            audioUrl?: string;
        };
        AddDeckWordsDto: {
            words: components["schemas"]["DeckWordItemDto"][];
        };
        CreateWordDto: {
            /** @example serendipity */
            word: string;
            /** @example kutilmagan yoqimli kashfiyot */
            translation: string;
            /** @example Finding that book was pure serendipity. */
            example?: string;
            /** @example https://cdn.example.com/audio/serendipity.mp3 */
            audioUrl?: string;
        };
        UpdateWordDto: {
            /** @example serendipity */
            word?: string;
            /** @example kutilmagan yoqimli kashfiyot */
            translation?: string;
            /** @example Finding that book was pure serendipity. */
            example?: string;
            /** @example https://cdn.example.com/audio/serendipity.mp3 */
            audioUrl?: string;
        };
        DailyWordResponseDto: {
            /**
             * Format: uuid
             * @description UserWord id (use in /learning/review)
             */
            id: string;
            /** Format: uuid */
            wordId: string;
            /** @example serendipity */
            word: string;
            /** @example kutilmagan yoqimli kashfiyot */
            translation: string;
            example?: Record<string, never>;
            /**
             * @example NEW
             * @enum {string}
             */
            status: "NEW" | "LEARNING" | "LEARNED";
            /** @example 0 */
            repetitionCount: number;
        };
        ReviewResultDto: {
            /** Format: uuid */
            id: string;
            /** @example serendipity */
            word: string;
            /**
             * @example LEARNING
             * @enum {string}
             */
            status: "NEW" | "LEARNING" | "LEARNED";
            /** @example 3 */
            repetitionCount: number;
            /**
             * @description Days until the next scheduled review
             * @example 6
             */
            interval: number;
            /**
             * Format: date-time
             * @description When this word is next due for review
             */
            nextReviewAt: string;
        };
        ReviewWordDto: {
            /**
             * Format: uuid
             * @description ID of the UserWord (not the Word itself)
             * @example 7a1e0b8f-9c12-4d3a-b8e7-65b1d3c9c2f4
             */
            userWordId: string;
            /**
             * @description Recall quality. AGAIN = failed (re-learn), HARD/GOOD/EASY = successful recall feeding the SM-2 schedule.
             * @example GOOD
             * @enum {string}
             */
            rating: "AGAIN" | "HARD" | "GOOD" | "EASY";
        };
        TestQuestionDto: {
            /** Format: uuid */
            wordId: string;
            /** @example serendipity */
            word: string;
            /**
             * @example [
             *       "kutilmagan yoqimli kashfiyot",
             *       "jadval",
             *       "iqtisodiy",
             *       "lazzat"
             *     ]
             */
            options: string[];
        };
        StartTestResponseDto: {
            /**
             * Format: uuid
             * @description Pass this back to POST /tests/submit when finished
             */
            testId: string;
            questions: components["schemas"]["TestQuestionDto"][];
        };
        TestQuestionResultDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            wordId: string;
            /** @description Null if the question was left unanswered */
            selectedAnswer: Record<string, never> | null;
            correctAnswer: string;
        };
        SubmitTestResponseDto: {
            /** Format: uuid */
            testId: string;
            /** @example 4 */
            score: number;
            /** @example 5 */
            total: number;
            /** @example 80 */
            percentage: number;
            questions: components["schemas"]["TestQuestionResultDto"][];
        };
        TestAnswerDto: {
            /**
             * Format: uuid
             * @example b2c1a0d3-5e4f-6789-abcd-ef0123456789
             */
            wordId: string;
            /** @example kutilmagan yoqimli kashfiyot */
            selectedAnswer: string;
        };
        SubmitTestDto: {
            /**
             * Format: uuid
             * @description The id returned by POST /tests/start
             * @example a1b2c3d4-5e6f-7890-abcd-ef0123456789
             */
            testId: string;
            answers: components["schemas"]["TestAnswerDto"][];
        };
        VocabularyStatsDto: {
            /** @example 42 */
            total: number;
            /** @example 10 */
            new: number;
            /** @example 22 */
            learning: number;
            /** @example 10 */
            learned: number;
            /**
             * @description Percentage of learned words (0–100)
             * @example 24
             */
            progressPercentage: number;
        };
        RecentTestDto: {
            /** Format: uuid */
            id: string;
            /** @example 4 */
            score: number;
            /** @example 5 */
            totalQuestions: number;
            /** Format: date-time */
            createdAt: string;
        };
        TestStatsDto: {
            /** @example 12 */
            total: number;
            /**
             * @description Average score across all tests
             * @example 3.8
             */
            averageScore: number;
            recent: components["schemas"]["RecentTestDto"][];
        };
        StreakStatsDto: {
            /**
             * @description Consecutive active days ending today (or yesterday if not yet reviewed today)
             * @example 5
             */
            current: number;
            /**
             * @description Longest consecutive active-day run ever
             * @example 12
             */
            longest: number;
            /**
             * @description Reviews completed today (UTC)
             * @example 8
             */
            todayCount: number;
            /**
             * @description User's daily review goal
             * @example 20
             */
            dailyGoal: number;
            /**
             * @description Whether todayCount has reached dailyGoal
             * @example false
             */
            goalMet: boolean;
        };
        ProgressResponseDto: {
            vocabulary: components["schemas"]["VocabularyStatsDto"];
            tests: components["schemas"]["TestStatsDto"];
            streak: components["schemas"]["StreakStatsDto"];
        };
        TrendPointDto: {
            /**
             * @description UTC calendar day
             * @example 2026-06-29
             */
            date: string;
            /**
             * @description Reviews completed on this day
             * @example 12
             */
            count: number;
        };
        DeckProgressDto: {
            /** Format: uuid */
            id: string;
            /** @example Travel Essentials */
            title: string;
            /**
             * @example A2
             * @enum {string|null}
             */
            level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2" | null;
            /**
             * @description Curated system deck
             * @example true
             */
            isSystem: boolean;
            /**
             * @description Words in the deck the user is tracking
             * @example 40
             */
            total: number;
            /** @example 10 */
            new: number;
            /** @example 22 */
            learning: number;
            /** @example 8 */
            learned: number;
            /**
             * @description Percentage of learned words (0–100)
             * @example 20
             */
            progressPercentage: number;
        };
        LeechWordDto: {
            /** Format: uuid */
            wordId: string;
            /** @example ubiquitous */
            word: string;
            /** @example hamma joyda mavjud */
            translation: string;
            /**
             * @description Times the card was failed after graduating
             * @example 6
             */
            lapses: number;
            /** @enum {string} */
            status: "NEW" | "LEARNING" | "LEARNED";
            /** Format: date-time */
            lastReviewedAt: Record<string, never> | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User created and authenticated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["AuthResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["AuthResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["AuthResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Refresh token is missing, invalid, expired, or reused */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Refresh token revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Logged out"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            /** @description Reset link sent if the account exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "If that email is registered, a reset link has been sent"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            /** @description Password reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Password has been reset"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Token is invalid, expired, or already used */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_requestEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification email sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Verification email sent"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            /** @description Email verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Email verified"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Token is invalid, expired, or already used */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["UserResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UsersController_deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountDto"];
            };
        };
        responses: {
            /** @description Account deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Account deleted"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Current password is incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Returns the updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["UserResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UsersController_onboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingDto"];
            };
        };
        responses: {
            /** @description Returns the onboarded user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["UserResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description One of the deckIds does not exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    UsersController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Password updated successfully"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description New password is the same as current, or fails validation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Current password is incorrect */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    DecksController_findAll: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page (capped at 100) */
                limit?: number;
                /** @description Filter by CEFR level */
                level?: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
                /** @description Case-insensitive title search */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: {
                            items: components["schemas"]["DeckResponseDto"][];
                            /** @example 137 */
                            total: number;
                            /** @example 1 */
                            page: number;
                            /** @example 20 */
                            limit: number;
                            /** @example true */
                            hasMore: boolean;
                        };
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    DecksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeckDto"];
            };
        };
        responses: {
            /** @description Deck created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["DeckResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    DecksController_findMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["DeckResponseDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    DecksController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["DeckDetailResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Deck not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    DecksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deck deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Deck deleted successfully"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description You can only edit your own decks */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Deck not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    DecksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeckDto"];
            };
        };
        responses: {
            /** @description Deck updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["DeckResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description You can only edit your own decks */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Deck not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    DecksController_enroll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["EnrollResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Deck not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    DecksController_addWords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDeckWordsDto"];
            };
        };
        responses: {
            /** @description Words added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["AddDeckWordsResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description You can only edit your own decks */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Deck not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    DecksController_removeWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                wordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Word removed from deck */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Word removed from deck"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description You can only edit your own decks */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Deck or word not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AdminDecksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeckDto"];
            };
        };
        responses: {
            /** @description System deck created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["DeckResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Requires the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AdminDecksController_addWords: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDeckWordsDto"];
            };
        };
        responses: {
            /** @description Words added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["AddDeckWordsResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Requires the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Deck not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    AdminDecksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deck deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Deck deleted successfully"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Requires the ADMIN role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Deck not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    WordsController_findAll: {
        parameters: {
            query?: {
                /** @description 1-based page number */
                page?: number;
                /** @description Items per page (capped at 100) */
                limit?: number;
                /** @description Filter by the learning status of the word */
                status?: "NEW" | "LEARNING" | "LEARNED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: {
                            items: components["schemas"]["WordResponseDto"][];
                            /** @example 137 */
                            total: number;
                            /** @example 1 */
                            page: number;
                            /** @example 20 */
                            limit: number;
                            /** @example true */
                            hasMore: boolean;
                        };
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    WordsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWordDto"];
            };
        };
        responses: {
            /** @description Word created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["WordResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    WordsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Word deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @example {
                         *       "message": "Word deleted successfully"
                         *     }
                         */
                        data?: unknown;
                        /** Format: date-time */
                        timestamp?: string;
                    };
                };
            };
            /** @description Word belongs to another user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Word not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    WordsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWordDto"];
            };
        };
        responses: {
            /** @description Word updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["WordResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Word belongs to another user */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
            /** @description Word not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    LearningController_getDailyWords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["DailyWordResponseDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    LearningController_reviewWord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewWordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["ReviewResultDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description UserWord does not exist or does not belong to user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    TestsController_startTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["StartTestResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
            /** @description Not enough words to start a test */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponseDto"];
                };
            };
        };
    };
    TestsController_submitTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["SubmitTestResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    ProgressController_getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["ProgressResponseDto"];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    ProgressController_getTrends: {
        parameters: {
            query?: {
                /** @description Size of the trailing window in days (ending today, UTC) */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["TrendPointDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    ProgressController_getDeckProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["DeckProgressDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    ProgressController_getLeeches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        data: components["schemas"]["LeechWordDto"][];
                        /** Format: date-time */
                        timestamp: string;
                    };
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
